# Generated by Django 5.1 on 2024-09-21 17:27

import ckeditor.fields
import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg'])])),
                ('title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ge', models.CharField(blank=True, max_length=150, null=True)),
                ('article_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('article_ge', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity/')),
                ('title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ge', models.CharField(blank=True, max_length=150, null=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_ge', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('article_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('article_ge', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=75, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ('-created_on',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('map_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact Info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text_en', models.CharField(blank=True, max_length=150, null=True)),
                ('header_text_ge', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('instagram_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('youtube_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('twitter_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
            ],
            options={
                'verbose_name': 'General Item',
                'verbose_name_plural': 'General Items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_image', models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg'])])),
                ('welcome_title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('welcome_title_ge', models.CharField(blank=True, max_length=100, null=True)),
                ('welcome_description_en', models.TextField(blank=True, null=True)),
                ('welcome_description_ge', models.TextField(blank=True, null=True)),
                ('activities_title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('activities_title_ge', models.CharField(blank=True, max_length=150, null=True)),
                ('activities_description_en', models.TextField(blank=True, null=True)),
                ('activities_description_ge', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page Items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg', 'svg'])])),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('web_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ('id',),
                'managed': True,
            },
        ),
    ]
