# Generated by Django 5.0.1 on 2024-10-13 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='toolkits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'png', 'jpg'])], verbose_name='Toolkit Picture')),
                ('url_en', models.FileField(blank=True, null=True, upload_to='toolkits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url En')),
                ('title_en', models.CharField(blank=True, max_length=25, null=True, verbose_name='Title En')),
                ('subtitle_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle En')),
                ('url_de', models.FileField(blank=True, null=True, upload_to='toolkits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url De')),
                ('title_de', models.CharField(blank=True, max_length=25, null=True, verbose_name='Title De')),
                ('subtitle_de', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle De')),
                ('url_ro', models.FileField(blank=True, null=True, upload_to='toolkits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url Ro')),
                ('title_ro', models.CharField(blank=True, max_length=25, null=True, verbose_name='Title Ro')),
                ('subtitle_ro', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle Ro')),
                ('url_lv', models.FileField(blank=True, null=True, upload_to='toolkits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url Lv')),
                ('title_lv', models.CharField(blank=True, max_length=25, null=True, verbose_name='Title Lv')),
                ('subtitle_lv', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle Lv')),
                ('url_tr', models.FileField(blank=True, null=True, upload_to='toolkits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url Tr')),
                ('title_tr', models.CharField(blank=True, max_length=25, null=True, verbose_name='Title Tr')),
                ('subtitle_tr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle Tr')),
            ],
            options={
                'verbose_name': 'Toolkit',
                'verbose_name_plural': 'Toolkits',
                'db_table': 'Toolkit',
                'ordering': ('id',),
                'managed': True,
            },
        ),
    ]
