# Generated by Django 5.0.1 on 2024-10-23 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_title_gallery_title_de_gallery_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_en', models.FileField(blank=True, null=True, upload_to='guides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url English Guide')),
                ('title_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title English')),
                ('url_de', models.FileField(blank=True, null=True, upload_to='guides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url German Guide')),
                ('title_de', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title German')),
            ],
            options={
                'verbose_name': 'Guide',
                'verbose_name_plural': 'Guides',
                'db_table': 'Guide',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_en', models.FileField(blank=True, null=True, upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url English Report')),
                ('title_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title English')),
                ('url_de', models.FileField(blank=True, null=True, upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url German Report')),
                ('title_de', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title German')),
            ],
            options={
                'verbose_name': 'Project Report',
                'verbose_name_plural': 'Project Reports',
                'db_table': 'Project Report',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shadowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_en', models.FileField(blank=True, null=True, upload_to='shadowing/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url English Shadowing')),
                ('title_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title English')),
                ('url_de', models.FileField(blank=True, null=True, upload_to='shadowing/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url German Shadowing')),
                ('title_de', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title German')),
            ],
            options={
                'verbose_name': 'Job Shadowing Report',
                'verbose_name_plural': 'Job Shadowing Reports',
                'db_table': 'Job Shadowing Report',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Toolkit',
        ),
    ]
