# Generated by Django 5.0.1 on 2024-10-23 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_guide_report_shadowing_delete_gallery_delete_toolkit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='url_de',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='url_en',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='report',
            name='url_de',
        ),
        migrations.RemoveField(
            model_name='report',
            name='url_en',
        ),
        migrations.RemoveField(
            model_name='shadowing',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='shadowing',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='shadowing',
            name='url_de',
        ),
        migrations.RemoveField(
            model_name='shadowing',
            name='url_en',
        ),
        migrations.AddField(
            model_name='guide',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='guide',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='guides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url Guide'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url Report'),
        ),
        migrations.AddField(
            model_name='shadowing',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='shadowing',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='shadowing/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Url Job Shadowing'),
        ),
        migrations.CreateModel(
            name='ActivitySliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_slider/')),
                ('title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ge', models.CharField(blank=True, max_length=150, null=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.activity')),
            ],
            options={
                'verbose_name': 'Activity Slider Image',
                'verbose_name_plural': 'Activity Slider Images',
                'managed': True,
            },
        ),
    ]
